export const qk = {
    outlets: ['outlets'] as const,
    outlet: (slug: string) => ['outlets', slug] as const,
    menuCategories: ['menu-categories'] as const,
    menuItems: (params?: Record<string, unknown>) => ['menu-items', params ?? null] as const,
    menuItem: (slug: string) => ['menu-items', slug] as const,
    gallery: (category?: string) => ['gallery', category ?? null] as const,
    testimonials: (featured?: boolean) => ['testimonials', featured ?? null] as const,
    promotions: ['promotions'] as const,
    siteSettings: ['site-settings'] as const,
    me: ['admin', 'me'] as const,
    adminDashboard: ['admin', 'dashboard'] as const,
    adminMenuItems: (params?: Record<string, unknown>) => ['admin', 'menu-items', params ?? null] as const,
    adminReservations: (params?: Record<string, unknown>) => ['admin', 'reservations', params ?? null] as const,
    adminMessages: (params?: Record<string, unknown>) => ['admin', 'contact-messages', params ?? null] as const,
    adminEventInquiries: (params?: Record<string, unknown>) => ['admin', 'event-inquiries', params ?? null] as const,
    adminGallery: (params?: Record<string, unknown>) => ['admin', 'gallery', params ?? null] as const,
    adminCategories: ['admin', 'menu-categories'] as const,
    adminTestimonials: ['admin', 'testimonials'] as const,
    adminPromotions: ['admin', 'promotions'] as const,
};
